version: '2'
services:
  mentorcarpatin-app:
    image: mentorcarpatin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mentorcarpatin-postgresql:5432/MentorCarpatin
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mentorcarpatin-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mentorcarpatin-elasticsearch:9200
    ports:
      - 8080:8080
  mentorcarpatin-postgresql:
    extends:
      file: postgresql.yml
      service: mentorcarpatin-postgresql
  mentorcarpatin-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mentorcarpatin-elasticsearch
